### ISSUE TITLE
Issue while using this module 

### ISSUE THREAD

**Issue by bipul34** [ansible-collections/kubernetes.core#387]
Hi , I am facing issue while trying to use this module for creating k8s objects 

**SUMMARY**
kubernetes.core.k8s hat can't create objects

**ISSUE TYPE**
Bug Report

**COMPONENT NAME**
kubernetes.core.k8s

**ANSIBLE VERSION**

```
ansible 2.9.17
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

pip3 list  | grep kubernetes
kubernetes (22.6.0)
```

**STEPS TO REPRODUCE**

run below playbook 

Playbook :  
```yaml
---
- hosts: master
  gather_facts: false
  collections:
    - kubernetes.core
  tasks:
  - name: Create a k8s namespace
    kubernetes.core.k8s:
      name: testing
      api_version: v1
      kind: Namespace
      state: present
```

**EXPECTED RESULTS**
The module create the object 

**ACTUAL RESULTS**

Error with -vvv (trace back)

```
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/.ansible/collections/ansible_collections/kubernetes/core/plugins/action/k8s.py", line 273, in run
    module_return = self._execute_module(module_name=self._task.action, module_args=new_module_args, task_vars=task_vars)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 796, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 190, in _configure_module
    environment=final_environment)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 1258, in modify_module
    environment=environment)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 1095, in _find_module_utils
    py_module_cache, zf)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 886, in recursive_finder
    py_module_names, py_module_cache, zf)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 731, in recursive_finder
    [os.path.join(*py_module_name[:-idx])])
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 650, in __init__
    self.get_source()
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 665, in get_source
    pkg = import_module(self._package_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/ansible/utils/collection_loader.py", line 112, in load_module
    mod = self._find_module(fullname, None, load=True)[1]
  File "/usr/lib/python2.7/site-packages/ansible/utils/collection_loader.py", line 226, in _find_module
    code_object = compile(source=source, filename=source_path, mode='exec', flags=0, dont_inherit=True)
  File "/root/.ansible/collections/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py", line 123
    return abs_remote_tmp + f"/turbo_mode.{self.collection_name}.socket"
                                                                       ^
SyntaxError: invalid syntax

fatal: [192.168.100.138]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

```

**Comment by asmacdo** [comment]
@bipul34 thanks for filing the issue. 

Could you please send us the version of your kubernetes.core collection?

**Comment by Akasurde** [comment]
@bipul34 Thanks for reporting this issue. You are using Python 2 which is EOL. Also, this collection requires [Python 3.6+](https://github.com/ansible-collections/kubernetes.core#python-support). Please update/upgrade your Python and re-try. Thanks.
