### ISSUE TITLE
k8s_cp failing with an internal syntax error

### ISSUE THREAD

**Issue by tardis4500** [ansible-collections/kubernetes.core#402]
##### SUMMARY
k8s_cp failing with an internal syntax error

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s_cp

##### ANSIBLE VERSION
```
ansible [core 2.12.3]
  config file = /home/jgs10292/.ansible.cfg
  configured module search path = ['/home/jgs10292/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jgs10292/.virtualenvs/tntmgr-api/lib/python3.9/site-packages/ansible
  ansible collection location = /home/jgs10292/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jgs10292/.virtualenvs/tntmgr-api/bin/ansible
  python version = 3.9.10 (main, Jan 24 2022, 11:12:09) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
kubernetes.core 2.2.3
```

##### CONFIGURATION
ansible-config dump --only-changed returns nothing

##### OS / ENVIRONMENT
Target OS /etc/os-release
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

##### STEPS TO REPRODUCE
```yaml
- name: Add the server
  hosts: localhost
  gather_facts: false
  tasks:
    - name: add the database host
      add_host:
        name: target-host
        ansible_shell_allow_world_readable_temp: yes

- name: Test Kubernetes file transfer
  hosts: all
  remote_user: your-remote-user
  become: yes
  become_user: root
  tasks:
  - kubernetes.core.k8s_cp:
      local_path: some-local-file
      remote_path: /some-remote-path/some-local-file
      kubeconfig: path-to-kubeconfig
      context: some-context
      namespace: the-namespace
      pod: the-pod
```

##### EXPECTED RESULTS
The desired file should be copied to the target k8s cluster.

##### ACTUAL RESULTS
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/jgs10292_ansible_tmp/ansible-tmp-1647015036.0900698-5101-235100560040231/AnsiballZ_k8s_cp.py", line 107, in <module>
    _ansiballz_main()
  File "/tmp/jgs10292_ansible_tmp/ansible-tmp-1647015036.0900698-5101-235100560040231/AnsiballZ_k8s_cp.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/jgs10292_ansible_tmp/ansible-tmp-1647015036.0900698-5101-235100560040231/AnsiballZ_k8s_cp.py", line 48, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 170, in run_module
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib64/python2.7/runpy.py", line 113, in _get_module_details
    code = loader.get_code(mod_name)
  File "/tmp/ansible_kubernetes.core.k8s_cp_payload_s5T1eW/ansible_kubernetes.core.k8s_cp_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_cp.py", line 166
    class K8SCopy(metaclass=ABCMeta):
```

**Comment by gravesm** [comment]
The traceback appears to show you are running python 2.7 on the remote node. kubernetes.core 2+ does not support python 2.7. Could you ensure you are running a supported version of python and see if that fixes the problem?

**Comment by tardis4500** [comment]
That appears to be the problem. CentOS 7 has Python 2.7 installed as part of the OS and Ansible uses that by default. Using yum to install python3 and setting the host inventory variable "ansible_python_interpreter: /usr/bin/python3" resolves the issue.
