### ISSUE TITLE
k8s_info causes an unavoidable error when the API cannot accept the connection

### ISSUE THREAD

**Issue by sugitk** [ansible-collections/kubernetes.core#407]
##### SUMMARY
k8s_info causes an unavoidable error when the API cannot accept the connection

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

k8s_info

##### COLLECTION VERSION

```paste below
Collection      Version
--------------- -------
kubernetes.core 2.2.3  
```

##### STEPS TO REPRODUCE

1. define a task in a playbook

```
  k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: clusterversion
```

2. run the above playbook periodically during the upgrading the OCP cluster

##### EXPECTED RESULTS

Grabbing the connection error in the module so that we can retry the task.

##### ACTUAL RESULTS

When the OCP API cannot accept the connection during the rebooting the node or something, the k8s_info module shows an error like this: (hostname and sensitive information are masked)

~~~
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
    ssl_context=context)
  File "/usr/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 354, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 776, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1036, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/user123/.ansible/tmp/ansible-tmp-1646850721.6780913-270968-159374049705148/AnsiballZ_k8s_info.py", line 102, in <module>
    _ansiballz_main()
  File "/home/user123/.ansible/tmp/ansible-tmp-1646850721.6780913-270968-159374049705148/AnsiballZ_k8s_info.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user123/.ansible/tmp/ansible-tmp-1646850721.6780913-270968-159374049705148/AnsiballZ_k8s_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s_info', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_k8s_info_payload_me2dfbo8/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py", line 198, in <module>
  File "/tmp/ansible_k8s_info_payload_me2dfbo8/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py", line 194, in main
  File "/tmp/ansible_k8s_info_payload_me2dfbo8/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py", line 166, in execute_module
  File "/tmp/ansible_k8s_info_payload_me2dfbo8/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 305, in kubernetes_facts
  File "/tmp/ansible_k8s_info_payload_me2dfbo8/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 465, in wait
  File "/tmp/ansible_k8s_info_payload_me2dfbo8/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 380, in _wait_for
  File "/usr/lib/python3.6/site-packages/kubernetes/dynamic/client.py", line 107, in get
    return self.request('get', path, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/dynamic/client.py", line 55, in inner
    resp = func(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/dynamic/client.py", line 252, in request
    _return_http_data_only=params.get('_return_http_data_only', True)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 377, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 243, in GET
    query_params=query_params)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 216, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.xxxxxxxxxxxxxxxxxxxxxx', port=6443): Max retries exceeded with url: /apis/config.openshift.io/v1/clusterversions/version (Caused by ProtocolError('Connection aborted.', OSError(0, 'Error')))
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "api_key": "sha256~xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "api_version": "config.openshift.io/v1",
        "host": "https://api.xxxxxxxxxxxxxxxxxxxxxx:6443",
        "kind": "ClusterVersion",
        "module_args": {
            "api_key": "sha256~xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "api_version": "config.openshift.io/v1",
            "host": "https://api.xxxxxxxxxxxxxxxxxxxxxx:6443",
            "kind": "ClusterVersion",
            "name": "version",
            "validate_certs": false,
            "wait": true,
            "wait_condition": {
                "status": false,
                "type": "Progressing"
            },
            "wait_sleep": 300,
            "wait_timeout": 43200
        },
        "name": "version",
        "validate_certs": false,
        "wait": true,
        "wait_condition": {
            "status": false,
            "type": "Progressing"
        },
        "wait_sleep": 300,
        "wait_timeout": 43200
    },
    "rc": 1
}
MSG:
MODULE FAILURE
See stdout/stderr for the exact error
MODULE_STDERR:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
    ssl_context=context)
  File "/usr/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 354, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 776, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1036, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/user123/.ansible/tmp/ansible-tmp-1646850721.6780913-270968-159374049705148/AnsiballZ_k8s_info.py", line 102, in <module>
    _ansiballz_main()
  File "/home/user123/.ansible/tmp/ansible-tmp-1646850721.6780913-270968-159374049705148/AnsiballZ_k8s_info.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user123/.ansible/tmp/ansible-tmp-1646850721.6780913-270968-159374049705148/AnsiballZ_k8s_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s_info', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_k8s_info_payload_me2dfbo8/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py", line 198, in <module>
  File "/tmp/ansible_k8s_info_payload_me2dfbo8/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py", line 194, in main
  File "/tmp/ansible_k8s_info_payload_me2dfbo8/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py", line 166, in execute_module
  File "/tmp/ansible_k8s_info_payload_me2dfbo8/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 305, in kubernetes_facts
  File "/tmp/ansible_k8s_info_payload_me2dfbo8/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 465, in wait
  File "/tmp/ansible_k8s_info_payload_me2dfbo8/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 380, in _wait_for
  File "/usr/lib/python3.6/site-packages/kubernetes/dynamic/client.py", line 107, in get
    return self.request('get', path, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/dynamic/client.py", line 55, in inner
    resp = func(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/dynamic/client.py", line 252, in request
    _return_http_data_only=params.get('_return_http_data_only', True)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 377, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 243, in GET
    query_params=query_params)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 216, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.xxxxxxxxxxxxxxxxxxxxxx', port=6443): Max retries exceeded with url: /apis/config.openshift.io/v1/clusterversions/version (Caused by ProtocolError('Connection aborted.', OSError(0, 'Error')))
~~~

**Comment by abikouo** [comment]
@sugitk Thanks for raising this issue, could you please test using this PR #408 ?
Regards

**Comment by sugitk** [comment]
@abikouo Thank you very much, I will try it tomorrow

**Comment by sugitk** [comment]
@gravesm @abikouo 

Hi, do you have a plan for a new release that this PR is merged?
The customer is waiting for the fix in some weeks and I have to explain to him about the current situation as an Ansible technical support.

Thank you.
