### ISSUE TITLE
Cannot patch the default kubecontrollersconfiguration

### ISSUE THREAD

**Issue by dyipon** [ansible-collections/kubernetes.core#411]
##### SUMMARY
Cannot patch the default kubecontrollersconfiguration

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core.k8s_json_patch

##### ANSIBLE VERSION

```ansible [core 2.11.3]
  config file = /home/d/ansible-ipon/ansible/ansible.cfg
  configured module search path = ['/home/d/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/d/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 2.11.3
  libyaml = True

```

##### COLLECTION VERSION

```community.general 3.5.0

```

##### CONFIGURATION

```-

```

##### OS / ENVIRONMENT
debian bullseye

##### STEPS TO REPRODUCE

trying to use as ansible task this command:
```
kubectl patch kubecontrollersconfiguration default --type=json -p="[{ 'op': 'replace', 'path': '/spec/controllers/node/hostEndpoint/autoCreate', 'value': 'Enabled'}]"
```

```
- kubernetes.core.k8s_json_patch:
        kind: kubecontrollersconfiguration
        name: default
        patch:
          - op: replace
            patch: /spec/controllers/node/hostEndpoint/autoCreate
            value: Enabled
```

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):                                                                                                                           File "/tmp/ansible_kubernetes.core.k8s_json_patch_payload_6lth1lny/ansible_kubernetes.core.k8s_json_patch_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 388, in find_resource                                                                                                 File "/tmp/ansible_kubernetes.core.k8s_json_patch_payload_6lth1lny/ansible_kubernetes.core.k8s_json_patch_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 365, in _find_resource_with_prefix                                                                                    File "/tmp/ansible_kubernetes.core.k8s_json_patch_payload_6lth1lny/ansible_kubernetes.core.k8s_json_patch_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/client/discovery.py", line 182, in get                                                                                               kubernetes.dynamic.exceptions.ResourceNotFoundError: No matches found for {'prefix': None, 'api_version': 'v1', 'short_names': ['kubecontrollersconfiguration']}

During handling of the above exception, another exception occurred:...


```

**Comment by dyipon** [comment]
i just realized the typo in the docs: https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_json_patch_module.html

```
- op: replace
        **patch**: /spec/containers/0/image
        value: nginx
```

this should be **path**

**Comment by Akasurde** [comment]
resolved_by_pr #425
