### ISSUE TITLE
k8s_log module traceback when no resource found

### ISSUE THREAD

**Issue by tardis4500** [ansible-collections/kubernetes.core#479]
##### SUMMARY
When no pod is found, the k8s_log module fails with a Python traceback from the module rather than some kind of "resource not found' error

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s_log

##### ANSIBLE VERSION
```paste below
ansible [core 2.12.6]
  config file = /home/jgs10292/.ansible.cfg
  configured module search path = ['/home/jgs10292/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/ansible
  ansible collection location = /home/jgs10292/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jgs10292/.virtualenvs/tntmgr-apg/bin/ansible
  python version = 3.9.13 (main, May 31 2022, 10:51:09) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```paste below
kubernetes.core 2.3.1
```

##### CONFIGURATION
```paste below
(Intentionally left blank)
```

##### OS / ENVIRONMENT
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

##### STEPS TO REPRODUCE
You will need an appropriate values.yml file for your local values.
```yaml
- name: Test Bug
  hosts: localhost
  gather_facts: false
  vars_files:
    - values.yml
  tasks:
    - name: Get the logs from a pod by name
      kubernetes.core.k8s_log:
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ context }}"
        namespace: "{{ namespace }}"
        name: "{{ pod_name }}"
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "{{ gke_key }}"

    - name: Get the logs from a non-existent pod by name
      kubernetes.core.k8s_log:
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ context }}"
        namespace: "{{ namespace }}"
        name: "{{ pod_name }}-bogus"
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "{{ gke_key }}"
```

##### EXPECTED RESULTS
The second task should fail with an error similar to that returned by kubectl
```
Error from server (NotFound): pods "podname-bogus" not found
```

##### ACTUAL RESULTS
There is an internal traceback from the module.
```paste below
TASK [Get the logs from a non-existent pod by name] ************************************************************************************************************************task path: /mnt/c/Users/jgs10292/Downloads/playbook.yml:16
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jgs10292
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/jgs10292_ansible_tmp `"&& mkdir "` echo /tmp/jgs10292_ansible_tmp/ansible-tmp-1655303065.76282-5459-109273293688691 `" && echo ansible-tmp-1655303065.76282-5459-109273293688691="` echo /tmp/jgs10292_ansible_tmp/ansible-tmp-1655303065.76282-5459-109273293688691 `" ) && sleep 0'  
Using module file /home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/ansible_collections/kubernetes/core/plugins/modules/k8s_log.py
<127.0.0.1> PUT /home/jgs10292/.ansible/tmp/ansible-local-5431_t_epbiv/tmp4qavnorc TO /tmp/jgs10292_ansible_tmp/ansible-tmp-1655303065.76282-5459-109273293688691/AnsiballZ_k8s_log.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /tmp/jgs10292_ansible_tmp/ansible-tmp-1655303065.76282-5459-109273293688691/ /tmp/jgs10292_ansible_tmp/ansible-tmp-1655303065.76282-5459-109273293688691/AnsiballZ_k8s_log.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'GOOGLE_APPLICATION_CREDENTIALS=/home/jgs10292/.ssh/dbmanager_gcp_val.json /home/jgs10292/.virtualenvs/tntmgr-apg/bin/python /tmp/jgs10292_ansible_tmp/ansible-tmp-1655303065.76282-5459-109273293688691/AnsiballZ_k8s_log.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /tmp/jgs10292_ansible_tmp/ansible-tmp-1655303065.76282-5459-109273293688691/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 55, in inner
    resp = func(self, *args, **kwargs)
  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 247, in request
    return self.client.call_api(
  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '0b118845-1475-4b47-a829-9769d8afc22e', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 15 Jun 2022 14:24:26 GMT', 'Content-Length': '250'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \\"tenantmanager-test-6bc88d7649-hml6s-bogus\\" not found","reason":"NotFound","details":{"name":"tenantmanager-test-6bc88d7649-hml6s-bogus","kind":"pods"},"code":404}\n'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/jgs10292_ansible_tmp/ansible-tmp-1655303065.76282-5459-109273293688691/AnsiballZ_k8s_log.py", line 107, in <module>
    _ansiballz_main()
  File "/tmp/jgs10292_ansible_tmp/ansible-tmp-1655303065.76282-5459-109273293688691/AnsiballZ_k8s_log.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/jgs10292_ansible_tmp/ansible-tmp-1655303065.76282-5459-109273293688691/AnsiballZ_k8s_log.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s_log', init_globals=dict(_module_fqn='ansible_collections.kubernetes.core.plugins.modules.k8s_log', _modlib_path=modlib_path),
  File "/usr/local/lib/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_kubernetes.core.k8s_log_payload_rf22kuup/ansible_kubernetes.core.k8s_log_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_log.py", line 263, in <module>
  File "/tmp/ansible_kubernetes.core.k8s_log_payload_rf22kuup/ansible_kubernetes.core.k8s_log_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_log.py", line 259, in main
  File "/tmp/ansible_kubernetes.core.k8s_log_payload_rf22kuup/ansible_kubernetes.core.k8s_log_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_log.py", line 189, in execute_module
  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 107, in get
    return self.request('get', path, **kwargs)
  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 57, in inner
    raise api_exception(e)
kubernetes.dynamic.exceptions.NotFoundError: 404
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '0b118845-1475-4b47-a829-9769d8afc22e', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 15 Jun 2022 14:24:26 GMT', 'Content-Length': '250'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \\"tenantmanager-test-6bc88d7649-hml6s-bogus\\" not found","reason":"NotFound","details":{"name":"tenantmanager-test-6bc88d7649-hml6s-bogus","kind":"pods"},"code":404}\n'
Original traceback: 
  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 55, in inner
    resp = func(self, *args, **kwargs)

  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 247, in request
    return self.client.call_api(

  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,

  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(

  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,

  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,

  File "/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "context": "k8s_gke_ssa_val",
        "kubeconfig": "/tenantmanager/cfg/kubeconfig.yml",
        "module_args": {
            "context": "k8s_gke_ssa_val",
            "kubeconfig": "/tenantmanager/cfg/kubeconfig.yml",
            "name": "tenantmanager-test-6bc88d7649-hml6s-bogus",
            "namespace": "tenantmanager-devops"
        },
        "name": "tenantmanager-test-6bc88d7649-hml6s-bogus",
        "namespace": "tenantmanager-devops"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/dynamic/client.py\", line 55, in inner\n    resp = func(self, *args, **kwargs)\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/dynamic/client.py\", line 247, in request\n    return self.client.call_api(\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/api_client.py\", line 348, in call_api\n    return self.__call_api(resource_path, method,\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/api_client.py\", line 180, in __call_api\n    response_data = self.request(\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/api_client.py\", line 373, in request\n    return self.rest_client.GET(url,\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/rest.py\", line 239, in GET\n    return self.request(\"GET\", url,\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/rest.py\", line 233, in request\n    raise ApiException(http_resp=r)\nkubernetes.client.exceptions.ApiException: (404)\nReason: Not Found\nHTTP response headers: HTTPHeaderDict({'Audit-Id': '0b118845-1475-4b47-a829-9769d8afc22e', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 15 Jun 2022 14:24:26 GMT', 'Content-Length': '250'})\nHTTP response body: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"pods \\\\\"tenantmanager-test-6bc88d7649-hml6s-bogus\\\\\" not found\",\"reason\":\"NotFound\",\"details\":{\"name\":\"tenantmanager-test-6bc88d7649-hml6s-bogus\",\"kind\":\"pods\"},\"code\":404}\\n'\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/tmp/jgs10292_ansible_tmp/ansible-tmp-1655303065.76282-5459-109273293688691/AnsiballZ_k8s_log.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/tmp/jgs10292_ansible_tmp/ansible-tmp-1655303065.76282-5459-109273293688691/AnsiballZ_k8s_log.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/jgs10292_ansible_tmp/ansible-tmp-1655303065.76282-5459-109273293688691/AnsiballZ_k8s_log.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s_log', init_globals=dict(_module_fqn='ansible_collections.kubernetes.core.plugins.modules.k8s_log', _modlib_path=modlib_path),\n  File \"/usr/local/lib/python3.9/runpy.py\", line 225, in run_module\n    
return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_kubernetes.core.k8s_log_payload_rf22kuup/ansible_kubernetes.core.k8s_log_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_log.py\", line 263, in <module>\n  File \"/tmp/ansible_kubernetes.core.k8s_log_payload_rf22kuup/ansible_kubernetes.core.k8s_log_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_log.py\", line 259, in main\n  File \"/tmp/ansible_kubernetes.core.k8s_log_payload_rf22kuup/ansible_kubernetes.core.k8s_log_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_log.py\", line 189, in execute_module\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/dynamic/client.py\", line 107, in get\n    return self.request('get', path, **kwargs)\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/dynamic/client.py\", line 57, in inner\n    raise api_exception(e)\nkubernetes.dynamic.exceptions.NotFoundError: 404\nReason: Not Found\nHTTP response headers: HTTPHeaderDict({'Audit-Id': '0b118845-1475-4b47-a829-9769d8afc22e', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 15 Jun 2022 14:24:26 GMT', 'Content-Length': '250'})\nHTTP response body: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"pods \\\\\"tenantmanager-test-6bc88d7649-hml6s-bogus\\\\\" not found\",\"reason\":\"NotFound\",\"details\":{\"name\":\"tenantmanager-test-6bc88d7649-hml6s-bogus\",\"kind\":\"pods\"},\"code\":404}\\n'\nOriginal traceback: \n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/dynamic/client.py\", line 55, in inner\n    resp = func(self, *args, **kwargs)\n\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/dynamic/client.py\", line 247, in request\n    return self.client.call_api(\n\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/api_client.py\", line 348, in call_api\n    return self.__call_api(resource_path, method,\n\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/api_client.py\", line 180, in __call_api\n    response_data = self.request(\n\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/api_client.py\", line 373, in request\n    return self.rest_client.GET(url,\n\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/rest.py\", line 239, in GET\n    return self.request(\"GET\", url,\n\n  File \"/home/jgs10292/.virtualenvs/tntmgr-apg/lib/python3.9/site-packages/kubernetes/client/rest.py\", line 233, in request\n    raise ApiException(http_resp=r)\n\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by gravesm** [comment]
Thanks for filing the issue @tardis4500.
