### ISSUE TITLE
ModuleNotFoundError: No module named 'openshift.watch' - k8s_scale

### ISSUE THREAD

**Issue by Alffernandez** [ansible-collections/kubernetes.core#482]
##### SUMMARY
After upgrading to Rhel8, the Ansible module 'k8s_scale' stopped working:
```
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib64/python3.6/[runpy.py](https://runpy.py/)", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/[runpy.py](https://runpy.py/)", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/[runpy.py](https://runpy.py/)", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_k8s_scale_payload_1dj3n3xy/ansible_k8s_scale_payload.zip/ansible/modules/clustering/k8s/k8s_[scale.py](https://scale.py/)", line 129, in <module>
  File "/tmp/ansible_k8s_scale_payload_1dj3n3xy/ansible_k8s_scale_payload.zip/ansible/modules/clustering/k8s/k8s_[scale.py](https://scale.py/)", line 125, in main
  File "/tmp/ansible_k8s_scale_payload_1dj3n3xy/ansible_k8s_scale_payload.zip/ansible/module_utils/k8s/[scale.py](https://scale.py/)", line 141, in execute_module
  File "/tmp/ansible_k8s_scale_payload_1dj3n3xy/ansible_k8s_scale_payload.zip/ansible/module_utils/k8s/[scale.py](https://scale.py/)", line 170, in scale
  File "/tmp/ansible_k8s_scale_payload_1dj3n3xy/ansible_k8s_scale_payload.zip/ansible/module_utils/k8s/[scale.py](https://scale.py/)", line 192, in _create_stream
NameError: name 'watch' is not defined
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python3.6/[runpy.py](https://runpy.py/)\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/[runpy.py](https://runpy.py/)\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/[runpy.py](https://runpy.py/)\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_k8s_scale_payload_1dj3n3xy/ansible_k8s_scale_payload.zip/ansible/modules/clustering/k8s/k8s_[scale.py](https://scale.py/)\", line 129, in <module>\n  File \"/tmp/ansible_k8s_scale_payload_1dj3n3xy/ansible_k8s_scale_payload.zip/ansible/modules/clustering/k8s/k8s_[scale.py](https://scale.py/)\", line 125, in main\n  File \"/tmp/ansible_k8s_scale_payload_1dj3n3xy/ansible_k8s_scale_payload.zip/ansible/module_utils/k8s/[scale.py](https://scale.py/)\", line 141, in execute_module\n  File \"/tmp/ansible_k8s_scale_payload_1dj3n3xy/ansible_k8s_scale_payload.zip/ansible/module_utils/k8s/[scale.py](https://scale.py/)\", line 170, in scale\n  File \"/tmp/ansible_k8s_scale_payload_1dj3n3xy/ansible_k8s_scale_payload.zip/ansible/module_utils/k8s/[scale.py](https://scale.py/)\", line 192, in _create_stream\nNameError: name 'watch' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```
The Python3 module openshift.watch is completely missing
```
$ python3
Python 3.6.8 (default, Jan 14 2022, 11:04:20)
[GCC 8.5.0 20210514 (Red Hat 8.5.0-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openshift.watch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'openshift.watch'
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core.k8s_scale

##### ANSIBLE VERSION

ansible 2.9.27-1

##### COLLECTION VERSION

python3-kubernetes.noarch 12.0.1-1.el8
python3-openshift.noarch 1:0.12.1-1.el8

##### OS / ENVIRONMENT

RHEL 8

##### ACTUAL RESULTS

```
line 192, in _create_stream\nNameError: name 'watch' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
```

**Comment by gravesm** [comment]
@Alffernandez You are using a very old version of the kubernetes.core collection. It looks like `openshift.watch` was removed from the openshift package in version 0.9. Can you try upgrading to a more recent version of the collection?

**Comment by yurnov** [comment]
Triage note — re-checked against `main` @ `e475d06` (7.0.0-dev0).

This can no longer occur on any supported release.

The traceback is from `openshift.watch`, but the collection dropped the `openshift` Python
client entirely. `requirements.txt` on `main` is now:

```
kubernetes>=24.2.0
requests-oauthlib
jsonpatch
```

and `git grep "import openshift" -- plugins/` returns nothing. The code path that raised this
doesn't exist anymore.

**Suggest closing.**

---
_Part of a sweep over all 91 open issues; index in #1215. Happy to see this reopened if it can still be reproduced on a current release._
