### ISSUE TITLE
Remote apply of kubernetes CRD with property named self causes deserialization error

### ISSUE THREAD

**Issue by shauser** [ansible-collections/kubernetes.core#502]
##### SUMMARY

When executing a k8s apply remotely with a CRD containing a property called "self", the deserialization of the result causes the error `TypeError: __init__() got multiple values for argument 'self'`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/XXXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/tmp.N4qeCZPi4x/venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/XXXX/.ansible/collections:/usr/share/ansible/collections
  executable location = /tmp/tmp.N4qeCZPi4x/venv/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
kubernetes.core 2.3.2
```

##### CONFIGURATION

```paste below
# no changes to default configuration
```

##### OS / ENVIRONMENT

Ubuntu 20.04, venv with ansible==6.2.0, ansible-core==2.13.3, kubernetes==24.2.0

##### STEPS TO REPRODUCE

1. Create inventory with host `remote_host`
2. Put kubeconfig in /tmp/kubeconfig on remote host
3. Run `ansible-playbook -i inventory test.yaml`

```yaml
---
- name: Apply kustomize project to the cluster
  hosts: remote_host
  become: no
  remote_user: ansible
  gather_facts: false
  tasks:
  - name: k8s apply
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        metadata:
          name: fubars.test.local
        spec:
          group: test.local
          names:
            kind: FuBar
            plural: fubars
            singular: fubar
          scope: Namespaced
          versions:
          - name: v1alpha1
            schema:
              openAPIV3Schema:
                properties:
                  self:
                    type: string
                type: object
            served: true
            storage: true
      kubeconfig: "/tmp/kubeconfig"
      context: "cluster"
```

##### EXPECTED RESULTS

k8s apply should work remotely and on localhost without errors.

##### ACTUAL RESULTS

Full output: https://gist.github.com/shauser/b6f747f7436748a64eae39fa57b3bffe (hosts and file names modified to protect the innocent)
```paste below
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1661178300.543739-2200200-265332695394144/AnsiballZ_k8s.py", line 107, in <module>
    _ansiballz_main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1661178300.543739-2200200-265332695394144/AnsiballZ_k8s.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1661178300.543739-2200200-265332695394144/AnsiballZ_k8s.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s', init_globals=dict(_module_fqn='ansible_collections.kubernetes.core.plugins.modules.k8s', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_kubernetes.core.k8s_payload_mvb0bvup/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 486, in <module>
  File "/tmp/ansible_kubernetes.core.k8s_payload_mvb0bvup/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 482, in main
  File "/tmp/ansible_kubernetes.core.k8s_payload_mvb0bvup/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 459, in execute_module
  File "/tmp/ansible_kubernetes.core.k8s_payload_mvb0bvup/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 807, in execute_module
  File "/tmp/ansible_kubernetes.core.k8s_payload_mvb0bvup/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 905, in perform_action
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/client.py", line 112, in get
    return self.request('get', path, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/client.py", line 62, in inner
    return serializer(self, json.loads(resp.data.decode('utf8')))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py", line 296, in __init__
    self.attributes = self.__deserialize(instance)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py", line 301, in __deserialize
    return ResourceField(**{
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py", line 302, in <dictcomp>
    k: self.__deserialize(v) for k, v in field.items()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py", line 301, in __deserialize
    return ResourceField(**{
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py", line 302, in <dictcomp>
    k: self.__deserialize(v) for k, v in field.items()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py", line 305, in __deserialize
    return [self.__deserialize(item) for item in field]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py", line 305, in <listcomp>
    return [self.__deserialize(item) for item in field]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py", line 301, in __deserialize
    return ResourceField(**{
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py", line 302, in <dictcomp>
    k: self.__deserialize(v) for k, v in field.items()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py", line 301, in __deserialize
    return ResourceField(**{
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py", line 302, in <dictcomp>
    k: self.__deserialize(v) for k, v in field.items()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py", line 301, in __deserialize
    return ResourceField(**{
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py", line 302, in <dictcomp>
    k: self.__deserialize(v) for k, v in field.items()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py", line 301, in __deserialize
    return ResourceField(**{
TypeError: __init__() got multiple values for argument 'self'
```

**Comment by gravesm** [comment]
@shauser Could you double check that you are using the latest version of the python kubernetes library on your remote host? I believe this is a duplicate of https://github.com/ansible-collections/kubernetes.core/issues/385. The bug in the kubernetes library has been fixed as of 24.2.0. I tested locally and can reproduce your problem with kubernetes==23.6.0 but it works fine with kubernetes==24.2.0.

**Comment by shauser** [comment]
Thanks, that would explain why we had it only remotely and not locally and also why I didn't find the other issue.

The problem is indeed solved with 24.2.0.
