### ISSUE TITLE
Server side apply broken in kubernetes >= 25.3.0

### ISSUE THREAD

**Issue by gravesm** [ansible-collections/kubernetes.core#548]
##### SUMMARY

Something changed in version 25 of the kubernetes library. I don't see anything in the changelog, but using server side apply now fails when the kubernetes library version is 25.3.0+. The likely candidate is https://github.com/ansible-collections/kubernetes.core/blob/69304d1c3b1d9cce8aba9343c4da433191be4ce9/plugins/module_utils/apply.py#L134.

See: https://github.com/ansible-collections/kubernetes.core/issues/547#issuecomment-1332554709

##### ISSUE TYPE
- Bug Report

##### COLLECTION VERSION

```paste below
2.3.2
```

##### STEPS TO REPRODUCE

The following playbook works as expected when kubernetes==24.2.0 and fails when kubernetes=25.3.0.

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - kubernetes.core.k8s:
        apply: true
        server_side_apply:
          field_manager: ansible
        definition:
          kind: Namespace
          apiVersion: v1
          metadata:
            name: testing

```

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/home/mgraves/.ansible/tmp/ansible-tmp-1669834036.478591-2018817-17689802905430/AnsiballZ_k8s.py", line 107, in <module>
    _ansiballz_main()
  File "/home/mgraves/.ansible/tmp/ansible-tmp-1669834036.478591-2018817-17689802905430/AnsiballZ_k8s.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/mgraves/.ansible/tmp/ansible-tmp-1669834036.478591-2018817-17689802905430/AnsiballZ_k8s.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s', init_globals=dict(_module_fqn='ansible_collections.kubernetes.core.plugins.modules.k8s', _modlib_path=modlib_path),
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_kubernetes.core.k8s_payload_ppk312hc/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 486, in <module>
  File "/tmp/ansible_kubernetes.core.k8s_payload_ppk312hc/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 482, in main
  File "/tmp/ansible_kubernetes.core.k8s_payload_ppk312hc/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 459, in execute_module
  File "/tmp/ansible_kubernetes.core.k8s_payload_ppk312hc/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 807, in execute_module
  File "/tmp/ansible_kubernetes.core.k8s_payload_ppk312hc/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 1114, in perform_action
  File "/tmp/ansible_kubernetes.core.k8s_payload_ppk312hc/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/k8sdynamicclient.py", line 45, in apply
  File "/tmp/ansible_kubernetes.core.k8s_payload_ppk312hc/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/apply.py", line 136, in k8s_apply
  File "/home/mgraves/git/ansible/venv-3.9/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 164, in server_side_apply
    return self.request('patch', path, body=body, force_conflicts=force_conflicts, **kwargs)
  File "/home/mgraves/git/ansible/venv-3.9/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 55, in inner
    resp = func(self, *args, **kwargs)
  File "/home/mgraves/git/ansible/venv-3.9/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 270, in request
    api_response = self.client.call_api(
  File "/home/mgraves/git/ansible/venv-3.9/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/mgraves/git/ansible/venv-3.9/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/mgraves/git/ansible/venv-3.9/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 407, in request
    return self.rest_client.PATCH(url,
  File "/home/mgraves/git/ansible/venv-3.9/lib/python3.9/site-packages/kubernetes/client/rest.py", line 296, in PATCH
    return self.request("PATCH", url,
  File "/home/mgraves/git/ansible/venv-3.9/lib/python3.9/site-packages/kubernetes/client/rest.py", line 168, in request
    request_body = json.dumps(body)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

**Comment by flybyray** [comment]
[workarround](https://github.com/ansible-collections/kubernetes.core/compare/2.3.2...ndgit:kubernetes.core:2.3.2-flybyray-patch-1?expand=1)
