### ISSUE TITLE
Too many args passed to ResourceTimeout in k8s_scale.py

### ISSUE THREAD

**Issue by schwadim** [ansible-collections/kubernetes.core#583]
##### SUMMARY
In line [raise ResourceTimeout("Resource scaling timed out", **result)](https://github.com/ansible-collections/kubernetes.core/blob/3d313cf8379ddee0e17e5a6879a1c9a56e4891c5/plugins/modules/k8s_scale.py#L393) the dict result contains the key [duration](https://github.com/ansible-collections/kubernetes.core/blob/3d313cf8379ddee0e17e5a6879a1c9a56e4891c5/plugins/modules/k8s_scale.py#L386) which is not accepted by [ResourceTimeout](https://github.com/ansible-collections/kubernetes.core/blob/3d313cf8379ddee0e17e5a6879a1c9a56e4891c5/plugins/module_utils/k8s/exceptions.py#L10).

Instead of `**result` `result["result"]` should be passed I suppose.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s_scale

##### ANSIBLE VERSION

```paste below
irrelevant
```

##### COLLECTION VERSION

```paste below
kubernetes.core   2.4.0
```

##### CONFIGURATION

```paste below
irrelevant
```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

I expected to get such an error message:
```
fatal: [127.0.0.1]: FAILED! => {
    "changed": false
}

MSG:

Resource scaling timed out
```

##### ACTUAL RESULTS

Instead I got this one:

```paste below
MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/home/.../.ansible/tmp/ansible-tmp-1675920758.3932006-3314057-26480630831081
1/AnsiballZ_k8s_scale.py", line 107, in <module>
    _ansiballz_main()
  File "/home/.../.ansible/tmp/ansible-tmp-1675920758.3932006-3314057-264806308310811/AnsiballZ_k8s_scale.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/.../.ansible/tmp/ansible-tmp-1675920758.3932006-3314057-264806308310811/AnsiballZ_k8s_scale.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s_scale', init_globals=dict(_module_fqn='ansible_collections.kubernetes.core.plugins.modules.k8s_scale', _modlib_path=modlib_path),
  File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_k8s_scale_payload_g5du0zqa/ansible_k8s_scale_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_scale.py", line 422, in <module>
  File "/tmp/ansible_k8s_scale_payload_g5du0zqa/ansible_k8s_scale_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_scale.py", line 416, in main
  File "/tmp/ansible_k8s_scale_payload_g5du0zqa/ansible_k8s_scale_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_scale.py", line 299, in execute_module
  File "/tmp/ansible_k8s_scale_payload_g5du0zqa/ansible_k8s_scale_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_scale.py", line 393, in scale
TypeError: __init__() got an unexpected keyword argument 'duration'
```

**Comment by abikouo** [comment]
@schwadim thanks for raising the issue.
Would you please open a pull request to fix this?

**Comment by schwadim** [comment]
Sure! It will follow sometime today.
